import {
  Sun,
  Flame,
  Snowflake,
  Smile,
  Meh,
  Laugh,
  Frown,
  User,
  Users,
  Footprints,
  Sparkles,
  PartyPopper,
  Minus,
  Flower2,
  Shuffle,
  BedDouble,
  RefreshCw,
  MoveHorizontal,
  PersonStanding,
  Wind,
  Rotate3d,
  Circle,
  Hand,
  Heart,
  ThumbsUp,
  ShoppingBag,
  Backpack,
  BookOpen,
  GlassWater,
  Coffee,
  Smartphone,
  Glasses,
  Camera,
  SmartphoneCharging,
  Table2,
  Aperture,
  ArrowUpToLine,
  ArrowDownToLine,
  Armchair,
  UtensilsCrossed,
  Building2,
  Trees,
  ShoppingCart,
  Umbrella,
  TreePine,
  Wine,
  Dumbbell,
  Sparkle,
  Scissors,
  Waves,
  ArrowUp,
  ArrowDown,
  HatGlasses,
  Palette,
  Eye,
  type LucideIcon,
} from "lucide-react";

/** Icon per seeded preset id. Anything not listed falls back to the section
 * icon passed to <PresetChips fallbackIcon=...>. */
const ICONS: Record<string, LucideIcon> = {
  // lighting
  dia: Sun,
  "noite-quente": Flame,
  "noite-fria": Snowflake,
  // pose
  "mao-cintura": PersonStanding,
  cabelo: Wind,
  "perna-cruzada": PersonStanding,
  "mao-bolso": PersonStanding,
  "corpo-de-lado": MoveHorizontal,
  // expression
  sorrindo: Smile,
  "lingua-fora": Laugh,
  "cabeca-inclinada": Rotate3d,
  seria: Frown,
  // direction
  frente: User,
  costas: RefreshCw,
  lado: MoveHorizontal,
  // environment
  arrumado: Sparkles,
  "pouco-bagunçado": Shuffle,
  "tenis-no-chao": Footprints,
  "roupa-na-cama": BedDouble,
  "pessoas-ao-fundo": Users,
  decorado: Flower2,
  minimalista: Minus,
  festa: PartyPopper,
  // hand / object
  nada: Hand,
  paz: Hand,
  coracao: Heart,
  joia: ThumbsUp,
  bolsa: ShoppingBag,
  "bolsa-ombro": ShoppingBag,
  mochila: Backpack,
  livros: BookOpen,
  "stanley-rosa": GlassWater,
  cafe: Coffee,
  "celular-extra": Smartphone,
  oculos: Glasses,
  // shot type
  espelho: Camera,
  selfie: SmartphoneCharging,
  "apoiado-mesa": Table2,
  "traseira-05x": Aperture,
  "de-cima": ArrowDownToLine,
  "de-baixo": ArrowUpToLine,
  andando: Footprints,
  sentada: Armchair,
  // scene (text locations) — 'como-esta' (environment) reuses RefreshCw below
  "restaurante-chique": UtensilsCrossed,
  cafeteria: Coffee,
  elevador: Building2,
  "parque-municipal": Trees,
  shopping: ShoppingCart,
  praia: Umbrella,
  "rua-arborizada": TreePine,
  rooftop: Wine,
  academia: Dumbbell,
  "banheiro-lounge": Sparkle,
  // environment "como-esta" (keep the space as-is) — shared with hair "como-esta"
  "como-esta": RefreshCw,
  // hairstyle
  solto: Wind,
  "para-frente": ArrowDown,
  "para-tras": ArrowUp,
  rabo: PersonStanding,
  coque: Circle,
  "meio-preso": PersonStanding,
  trancas: Waves,
  bone: HatGlasses,
  "bone-rabo": HatGlasses,
  // hair texture
  liso: Minus,
  ondulado: Waves,
  cacheado: Waves,
  "mais-curto": Scissors,
  "mais-longo": Scissors,
  // makeup
  sem: Minus,
  natural: Sparkles,
  leve: Sparkles,
  glam: PartyPopper,
  sexy: Heart,
  "boca-marcada": Palette,
  // skin / sun tan
  "sem-marca": Minus,
  bronzeada: Sun,
  "rosto-sol": Sun,
  "corpo-marca": Sun,
  "rosto-corpo-sol": Sun,
  // new poses ("mao-cintura" already mapped above)
  "perna-atras": PersonStanding,
  "pernas-cruzadas-cintura": PersonStanding,
  "olhar-de-baixo": Eye,
  "mao-tapando-sol": Sun,
  "olhando-lateral": Eye,
};

export function iconForPreset(id: string, fallback: LucideIcon = Circle): LucideIcon {
  // "neutra" is used by both pose and expression — pick a sensible icon per context
  if (id === "neutra") return fallback === Smile ? Meh : PersonStanding;
  return ICONS[id] ?? fallback;
}
